import "dotenv/config";

export const ENV = {
  NODE_ENV: process.env.NODE_ENV ?? "development",
  PORT: Number(process.env.PORT) || 3000,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  DATABASE_URL: process.env.DATABASE_URL,

  CORS_ENABLED: process.env.CORS_ENABLED,
  CORS_ALLOWED_HEADERS: process.env.CORS_ALLOWED_HEADERS,
  CORS_ALLOWED_METHODS: process.env.CORS_ALLOWED_METHODS,
  CORS_ALLOWED_ORIGIN: process.env.CORS_ALLOWED_ORIGIN,
  CORS_ALLOW_CREDENTIALS: process.env.CORS_ALLOW_CREDENTIALS,

  RATE_LIMITER_DURARION: process.env.RATE_LIMITER_DURARION,
  RATE_LIMITER_ALLOWED_REQUESTS: process.env.RATE_LIMITER_ALLOWED_REQUESTS,

  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,

  REDIS_USER: process.env.REDIS_USER,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,

  RABBITMQ_URL: process.env.RABBITMQ_URL,
};
